M48
; DRILL file {KiCad 9.0.3} date 2025-08-12T15:30:23+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-12T15:30:23+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X63.574Y-64.008
T2
X35.56Y-60.96
X35.56Y-100.33
X259.08Y-60.96
X259.08Y-100.33
M30
