M48
; DRILL file {KiCad 9.0.3} date 2025-09-10T19:37:48+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-10T19:37:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X38.017Y-40.98
X38.017Y-43.52
T2
X67.892Y-41.148
T3
X36.875Y-171.9
X38.9Y-29.525
X213.575Y-172.0
X214.376Y-30.226
M30
